### ISSUE TITLE
Fix Document Expiring Section "e.map is not a function"

### ISSUE THREAD

**Issue by zenmastaflash** [zenmastaflash/fromany-country#24]
console log:

69-97c81b7a776b578f.js:1 TypeError: e.map is not a function
    at d (page-77f1ffc6c86a887e.js:1:6923)
    at rk (fd9d1056-838dc1e3bacb56fa.js:1:40395)
    at lI (fd9d1056-838dc1e3bacb56fa.js:1:59202)
    at iB (fd9d1056-838dc1e3bacb56fa.js:1:117301)
    at o4 (fd9d1056-838dc1e3bacb56fa.js:1:94657)
    at fd9d1056-838dc1e3bacb56fa.js:1:94479
    at o3 (fd9d1056-838dc1e3bacb56fa.js:1:94486)
    at oQ (fd9d1056-838dc1e3bacb56fa.js:1:91973)
    at oj (fd9d1056-838dc1e3bacb56fa.js:1:91398)
    at MessagePort.M (69-97c81b7a776b578f.js:1:80137)

**Comment by zenmastaflash** [comment]
fixed by correctly wrapping file
